# Generated by Django 5.1.6 on 2025-10-06 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partneractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: TikTok-канал о кулинарии', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название площадки')),
                ('description', models.CharField(help_text='Например: Блог о путешествиях', max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание площадки')),
                ('platform_type', models.CharField(choices=[('website', 'Веб-сайт'), ('social_networks', 'Социальные сети'), ('youtube', 'YouTube'), ('blog', 'Блог'), ('other', 'Другое')], max_length=20, verbose_name='Тип площадки')),
                ('url_or_id', models.CharField(help_text='Ссылка или идентификатор (@username, channel ID)', max_length=150, verbose_name='URL или ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked')], default='На модерации', verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True)),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_platforms', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'url_or_id'), name='unique_platform')],
            },
        ),
    ]
