# Generated by Django 5.1.6 on 2025-10-06 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerPayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_method', models.CharField(choices=[('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('e_wallet', 'Электронный кошелёк'), ('sbp', 'Система быстрых платежей (СБП)')], max_length=20, verbose_name='Способ вывода')),
                ('card_number', models.CharField(blank=True, help_text='Только цифры, до 19 символов', max_length=19, null=True, verbose_name='Номер карты')),
                ('cardholder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя владельца карты')),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер счёта')),
                ('bank_account_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Владелец счёта')),
                ('bank_account_bic', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК банка для банковского перевода')),
                ('e_wallet_identifier', models.CharField(blank=True, help_text='Номер кошелька, email или другой идентификатор', max_length=100, null=True, verbose_name='Идентификатор электронного кошелька')),
                ('sbp_identifier', models.CharField(blank=True, help_text='Телефон', max_length=100, null=True, verbose_name='Идентификатор СБП')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('active_payout_method', models.CharField(choices=[('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('e_wallet', 'Электронный кошелёк'), ('sbp', 'Система быстрых платежей (СБП)')], max_length=20, verbose_name='Активно')),
                ('partner', models.OneToOneField(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_settings', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Настройки вывода средств партнёра',
                'verbose_name_plural': 'Настройки вывода средств партнёров',
                'unique_together': {('partner', 'payout_method', 'bank_account_number'), ('partner', 'payout_method', 'card_number'), ('partner', 'payout_method', 'e_wallet_identifier'), ('partner', 'payout_method', 'sbp_identifier')},
            },
        ),
    ]
