# Generated by Django 5.1.6 on 2025-10-06 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partnerpayoutsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(300)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('wallet', 'Электронный кошелёк'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('sbp', 'Система быстрых платежей (СБП)')], default='card', max_length=20, verbose_name='Способ выплаты')),
                ('status', models.CharField(choices=[('В обработке', 'Pending'), ('Выплачено', 'Completed'), ('Отменено', 'Rejected')], default='В обработке', max_length=20, verbose_name='Статус транзакции')),
                ('rejection_reason', models.TextField(blank=True, help_text='Укажите причину, если транзакция отклонена', null=True, verbose_name='Причина отклонения')),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
    ]
