# Generated by Django 5.1.6 on 2025-10-07 06:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0007_projectparam'),
        ('partners', '0005_partnertransaction'),
        ('partnerships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='Сгенерированная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('partnership', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='partnerships.projectpartner', verbose_name='Сотрудничество партнёра с проектом')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='advertisers.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Партнёрская ссылка',
                'verbose_name_plural': 'Партнёрские ссылки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'is_active'], name='partners_pa_partner_2b4261_idx')],
            },
        ),
    ]
