# Generated by Django 5.1.6 on 2025-10-06 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sale', 'Новая продажа'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('clicks', 'Переходы по ссылке'), ('topup', 'Пополнение баланса'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Детали')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='advertisers.advertiserprofile', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Активность рекламодателя',
                'verbose_name_plural': 'Активности рекламодателей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advertiser', 'is_read'], name='advertisers_adverti_11c822_idx')],
            },
        ),
    ]
