# Generated by Django 5.1.6 on 2025-10-06 12:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0003_advertisertransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='ФИО ответственного лица')),
                ('organization_name', models.CharField(blank=True, default='', max_length=300, null=True, unique=True, verbose_name='Полное наименование организации')),
                ('legal_address', models.TextField(blank=True, help_text='Почтовый индекс, город, улица, дом', null=True, verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Email')),
                ('ogrn', models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='ОГРН / ОГРНИП')),
                ('inn', models.CharField(blank=True, default='', max_length=12, null=True, unique=True, verbose_name='ИНН')),
                ('checking_account', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Корреспондентский счёт')),
                ('bik', models.CharField(blank=True, default='', max_length=9, null=True, unique=True, verbose_name='БИК банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['organization_name'],
            },
        ),
    ]
