# Generated by Django 5.1.6 on 2025-10-06 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0004_advertiserrequisites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Интернет магазин', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название проекта')),
                ('description', models.CharField(help_text='Например: Интернет магазин с быстрой доставкой, дешёвыми ценами и большим ассортиментом', max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание проекта')),
                ('url', models.CharField(default='', help_text='Ссылка или идентификатор (@username, channel ID)', max_length=150, verbose_name='URL или ID')),
                ('new_cost_per_action', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Цена за действие')),
                ('cost_per_action', models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Цена за действие')),
                ('first_price', models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Первоначальная цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked')], default='На модерации', verbose_name='Статус')),
                ('link_template', models.CharField(blank=True, default=None, help_text='Введите адрес партнёрской ссылки и добавьте ниже необходимые параметры', max_length=500, null=True, verbose_name='Шаблон ссылки')),
                ('is_active', models.BooleanField(default=True)),
                ('advertiser', models.ForeignKey(limit_choices_to={'user_type': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
