# Generated by Django 5.1.6 on 2025-10-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0006_project_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя параметра')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('param_type', models.CharField(choices=[('required', 'Обязательный'), ('optional', 'Опциональный')], default='optional', max_length=10, verbose_name='Тип параметра')),
                ('example_value', models.CharField(blank=True, max_length=100, verbose_name='Пример значения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='advertisers.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Параметр проекта',
                'verbose_name_plural': 'Параметры проекта',
            },
        ),
    ]
