# Generated by Django 5.1.6 on 2025-10-01 12:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comment', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('status', models.CharField(choices=[('На модерации', 'Pending'), ('Опубликован', 'Published')], default='На модерации', verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзывы пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'indexes': [models.Index(fields=['user'], name='core_userre_user_id_5a14c7_idx'), models.Index(fields=['name'], name='core_userre_name_336f89_idx'), models.Index(fields=['comment'], name='core_userre_comment_cbe30a_idx'), models.Index(fields=['created_at'], name='core_userre_created_f98cf8_idx')],
            },
        ),
    ]
