# Generated by Django 5.1.6 on 2025-10-06 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('partner_app', '0109_migrate_advertiser_requisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='partner_app.user', verbose_name='Отзывы пользователя'),
        ),
    ]
