# Generated by Django 5.1.6 on 2025-06-20 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='new_id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        # ),
    ]
