# Generated by Django 5.1.6 on 2025-06-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0007_remove_user_new_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
