# Generated by Django 5.1.6 on 2025-06-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0009_alter_user_id'),
    ]

    operations = [
    ]
