# Generated by Django 5.1.6 on 2025-06-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0010_remove_old_id'),
    ]

    operations = [
    ]
