# Generated by Django 5.1.6 on 2025-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerprofile',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
