# Generated by Django 5.1.6 on 2025-06-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0012_partnerprofile_description_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
