# Generated by Django 5.1.6 on 2025-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0013_alter_partnerprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerprofile',
            name='description',
            field=models.CharField(default='Описание партнёра', max_length=200),
        ),
    ]
