# Generated by Django 5.1.6 on 2025-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0015_remove_partnerprofile_description_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='Описание', max_length=200),
        ),
    ]
