# Generated by Django 5.1.5 on 2025-06-26 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0017_alter_user_user_type_managerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: TikTok-канал о кулинарии', max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название площадки')),
                ('platform_type', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Веб-сайт'), ('other', 'Другое')], max_length=20, verbose_name='Тип площадки')),
                ('url_or_id', models.CharField(help_text='Ссылка или идентификатор (@username, channel ID)', max_length=150, verbose_name='URL или ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(default='На модерации', verbose_name='Статус')),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('partner', 'url_or_id'), name='unique_partner_platform')],
            },
        ),
    ]
