# Generated by Django 5.1.5 on 2025-06-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0018_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(choices=[('website', 'Веб-сайт'), ('social_networks', 'Социальные сети'), ('youtube', 'YouTube'), ('blog', 'Блог'), ('other', 'Другое')], max_length=20, verbose_name='Тип площадки'),
        ),
    ]
