# Generated by Django 5.1.6 on 2025-06-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0020_alter_platform_name_alter_platform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected')], default='На модерации', verbose_name='Статус'),
        ),
    ]
