# Generated by Django 5.1.6 on 2025-07-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0023_platform_is_active_alter_platform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='api_key',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
