# Generated by Django 5.1.5 on 2025-07-02 18:14

from django.db import migrations

def set_null_for_empty_api_key(apps, schema_editor):
    AdvertiserProfile = apps.get_model('partner_app', 'AdvertiserProfile')
    AdvertiserProfile.objects.filter(api_key='').update(api_key=None)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0025_alter_advertiserprofile_api_key_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(set_null_for_empty_api_key),
    ]
