# Generated by Django 5.1.5 on 2025-07-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0026_fix_advertiserprofile_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofile',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
