# Generated by Django 5.1.6 on 2025-07-03 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0028_alter_user_options_platform_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(help_text='Например: Блог о путешествиях', max_length=300, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание площадки'),
        ),
    ]
