# Generated by Django 5.1.6 on 2025-07-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0030_remove_projectpartner_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpartner',
            name='custom_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='status',
            field=models.CharField(choices=[('Активен', 'Active'), ('Приостановлен', 'Suspended'), ('Заблокировано', 'Blocked')], default='Активен', help_text='Подтверждён ли доступ партнёра к проекту', verbose_name='Статус взаимодействия'),
        ),
    ]
