# Generated by Django 5.1.6 on 2025-07-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0032_advertiserprofile_balance_partnerprofile_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpartner',
            options={'verbose_name': 'Участник проекта', 'verbose_name_plural': 'Участники проектов'},
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platform',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_platforms', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advertiser',
            field=models.ForeignKey(limit_choices_to={'user_type': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'partner'}, related_name='participating_projects', through='partner_app.ProjectPartner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёры проекта'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='custom_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Индивидуальная комиссия'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to='partner_app.project'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='status',
            field=models.CharField(choices=[('Активен', 'Active'), ('Приостановлен', 'Suspended'), ('Заблокировано', 'Blocked')], default='Активен', help_text='Подтверждён ли доступ партнёра к проекту', max_length=20, verbose_name='Статус взаимодействия'),
        ),
    ]
