# Generated by Django 5.1.5 on 2025-07-21 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0036_projectpartner_joined_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpartner',
            options={'verbose_name': 'Партнёрство в проекте'},
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='custom_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Комиссия партнёра'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата начала сотрудничества'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to='partner_app.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Приостановлен', 'Приостановлен'), ('Заблокировано', 'Заблокировано')], default='Активен', max_length=20, verbose_name='Статус сотрудничества'),
        ),
    ]
