# Generated by Django 5.1.5 on 2025-07-21 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0037_alter_projectpartner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpartner',
            options={'verbose_name': 'Партнёрство в проекте', 'verbose_name_plural': 'Партнёрства в проектах'},
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_link', to='partner_app.project')),
            ],
            options={
                'verbose_name': 'Партнёрская ссылка',
                'verbose_name_plural': 'Партнёрские ссылки',
            },
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='partner_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='partner_app.partnerlink', verbose_name='Партнёрская ссылка'),
        ),
    ]
