# Generated by Django 5.1.5 on 2025-07-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0041_remove_deleted_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpartner',
            name='partner_link',
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.TextField(blank=True, default=dict)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='partner_app.project')),
            ],
        ),
        migrations.DeleteModel(
            name='PartnerLink',
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['order_id'], name='partner_app_order_i_c7bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['created_at'], name='partner_app_created_d8d022_idx'),
        ),
    ]
