# Generated by Django 5.1.5 on 2025-07-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0042_remove_projectpartner_partner_link_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='meta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='partner_app.project'),
        ),
    ]
