# Generated by Django 5.1.5 on 2025-07-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0047_partnerlink_alter_projectpartner_partner_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlink',
            name='partnership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='partner_app.projectpartner', verbose_name='Проект'),
        ),
    ]
