# Generated by Django 5.1.6 on 2025-08-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0058_alter_conversion_options_partneractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneractivity',
            name='amount',
        ),
    ]
