# Generated by Django 5.1.5 on 2025-08-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0060_remove_partnerlink_income_remove_platform_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneractivity',
            name='activity_type',
            field=models.CharField(choices=[('sale', 'Новая продажа'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('clicks', 'Переходы по ссылке'), ('payout', 'Выплата'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип активности'),
        ),
        migrations.AlterField(
            model_name='partneractivity',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='partner_app.partnerprofile', verbose_name='Партнёр'),
        ),
        migrations.CreateModel(
            name='AdvertiserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sale', 'Новая продажа'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('clicks', 'Переходы по ссылке'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Детали')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='partner_app.advertiserprofile', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Активность рекламодателя',
                'verbose_name_plural': 'Активности рекламодателей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['advertiser', 'is_read'], name='partner_app_adverti_7c74b0_idx')],
            },
        ),
    ]
