# Generated by Django 5.1.6 on 2025-08-08 13:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0062_remove_conversion_partner_app_order_i_c7bba7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('wallet', 'Электронный кошелёк'), ('card', 'Банковская карта'), ('cash', 'Наличные'), ('bank_transfer', 'Банковский перевод'), ('crypto', 'Криптовалюта')], default='card', max_length=20, verbose_name='Способ выплаты')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('refunded', 'Возвращено'), ('canceled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус транзакции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('partner', models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
    ]
