# Generated by Django 5.1.6 on 2025-08-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0065_alter_partnerpayoutsettings_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertransaction',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Pending'), ('Выплачено', 'Completed'), ('Отменено', 'Rejected'), ('Заблокировано', 'Blocked')], default='В обработке', max_length=20, verbose_name='Статус транзакции'),
        ),
    ]
