# Generated by Django 5.1.6 on 2025-08-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0068_partnertransaction_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpayoutsettings',
            name='bank_name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Название банка'),
        ),
    ]
