# Generated by Django 5.1.6 on 2025-08-15 09:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0076_remove_projectpartner_custom_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.project'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='cost_per_action',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за действие'),
        ),
    ]
