# Generated by Django 5.1.6 on 2025-08-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0077_alter_conversion_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpartner',
            name='cost_per_action',
        ),
    ]
