# Generated by Django 5.1.5 on 2025-08-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0081_clickevent_advertiser_alter_clickevent_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='order_id',
        ),
    ]
