# Generated by Django 5.1.6 on 2025-08-29 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0088_remove_advertiserprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiseractivity',
            name='activity_type',
            field=models.CharField(choices=[('sale', 'Новая продажа'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('clicks', 'Переходы по ссылке'), ('topup', 'Пополнение баланса'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип активности'),
        ),
        migrations.CreateModel(
            name='AdvertiserRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_person', models.CharField(max_length=200, verbose_name='ФИО ответственного лица')),
                ('organization_name', models.CharField(max_length=300, verbose_name='Полное наименование организации')),
                ('legal_address', models.TextField(help_text='Почтовый индекс, город, улица, дом', verbose_name='Юридический адрес')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ogrn', models.CharField(max_length=15, unique=True, verbose_name='ОГРН / ОГРНИП')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('checking_account', models.CharField(max_length=20, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Корреспондентский счёт')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК банка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Юридическое лицо',
                'verbose_name_plural': 'Юридические лица',
                'ordering': ['organization_name'],
            },
        ),
    ]
