# Generated by Django 5.1.5 on 2025-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0095_alter_advertiserrequisites_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='ogrn',
            field=models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='ОГРН / ОГРНИП'),
        ),
    ]
