# Generated by Django 5.1.5 on 2025-09-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0096_alter_advertiserrequisites_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisertransaction',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
    ]
