# Generated by Django 5.1.6 on 2025-10-03 10:04

from django.db import migrations

def move_partners_to_new_app(apps, schema_editor):
    OldPartner = apps.get_model('partner_app', 'PartnerProfile')
    NewPartner = apps.get_model('partners', 'PartnerProfile')
    old_users = OldPartner.objects.select_related('user').all()
    User = apps.get_model('users', 'User')
    
    new_partners = []
    for old_user in old_users:

        user = User.objects.get(id=old_user.user.id)

        new_partner = NewPartner(
            id=old_user.id,
            user=user,
            balance=old_user.balance            
        )
        new_partners.append(new_partner)
    
    # Массовое создание (быстрее для больших объемов данных)
    NewPartner.objects.bulk_create(new_partners, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0100_auto_20251003_1021'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_partners_to_new_app),
    ]