# Generated by Django 5.1.6 on 2025-10-06 07:38

from django.db import migrations


def migrate_partner_transactions(apps,schema_editor):
    old_transaction = apps.get_model('partner_app','PartnerTransaction')
    NewTransaction = apps.get_model('partners','PartnerTransaction')
    old_transactions = old_transaction.objects.all()

    partner = apps.get_model('users','User')
   
    new_transactions = []

    for transaction in old_transactions:
        user = partner.objects.get(id = transaction.partner.id)

        new_transaction = NewTransaction(
            id=transaction.id,
            partner=user,
            date=transaction.date,
            amount=transaction.amount,
            payment_method=transaction.payment_method,
            status=transaction.status,
            rejection_reason=transaction.rejection_reason
        )
        new_transactions.append(new_transaction)

    NewTransaction.objects.bulk_create(new_transactions, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0104_auto_20251006_1016'),
        ('partners','0005_partnertransaction')
    ]

    operations = [
        migrations.RunPython(migrate_partner_transactions)
    ]
