# Generated by Django 5.1.6 on 2025-10-06 11:40

from django.db import migrations
def migrate_advertisers(apps, schema_editor):
    # Модели из старого и нового приложений
    OldAdvertiser = apps.get_model('partner_app', 'AdvertiserProfile')
    NewAdvertiser = apps.get_model('advertisers', 'AdvertiserProfile')
    User = apps.get_model('users', 'User')

    # Получаем все старые записи
    old_records = OldAdvertiser.objects.all()

    new_objects = []
    for old in old_records:
        try:
            user = User.objects.get(id=old.user.id)
        except User.DoesNotExist:
            continue  # Пропускаем, если пользователь был удалён

        new_obj = NewAdvertiser(
            id=old.id,
            user=user,
            api_key=old.api_key,
            balance=old.balance,
        )
        new_objects.append(new_obj)

    # Массовое создание (быстрее, чем по одному)
    NewAdvertiser.objects.bulk_create(new_objects, batch_size=1000)

    schema_editor.execute("""
        SELECT setval('advertisers_advertiserprofile_id_seq', 
        (SELECT COALESCE(MAX(id), 1) FROM advertisers_advertiserprofile), true);
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0105_auto_20251006_1038'),
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_advertisers)
    ]
