# Generated by Django 5.1.6 on 2025-10-06 12:02

from django.db import migrations


def migrate_advertiser_activity(apps,schema_editor):
    OldNotification = apps.get_model('partner_app', 'AdvertiserActivity')
    NewNotification = apps.get_model('advertisers', 'AdvertiserActivity')
    old_notifications = OldNotification.objects.all()
    Advertiser = apps.get_model('advertisers', 'AdvertiserProfile')
    
    new_partner_notifications = []
    for notification in old_notifications:

        user = Advertiser.objects.get(id=notification.advertiser.id)

        new_notification = NewNotification(
            id=notification.id,          
            advertiser=user,
            activity_type=notification.activity_type,
            title=notification.title,
            details=notification.details,
            is_read=notification.is_read,
            created_at=notification.created_at
        )
        new_partner_notifications.append(new_notification)
    
    NewNotification.objects.bulk_create(new_partner_notifications, batch_size=1000)


    schema_editor.execute("""
        SELECT setval('advertisers_advertiseractivity_id_seq', 
        (SELECT COALESCE(MAX(id), 1) FROM advertisers_advertiseractivity), true);
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0106_auto_20251006_1440'),
        ('advertisers','0002_advertiseractivity')
    ]

    operations = [
        migrations.RunPython(migrate_advertiser_activity)
    ]
