# Generated by Django 5.1.6 on 2025-10-06 14:24

from django.db import migrations


def migrate_partnerships(apps, schema_editor): 
    
    NewProject = apps.get_model('advertisers', 'Project') 
    oldProjectPartner = apps.get_model('partner_app', 'ProjectPartner')
    ProjectPartner = apps.get_model('partnerships', 'ProjectPartner')
    user = apps.get_model('users', 'User') 

    old_partnerships = oldProjectPartner.objects.all() 
    project_partner_instances = [] 
    for partnership in old_partnerships: 
        new_project = NewProject.objects.get(id=partnership.project.id) 
        new_partner = user.objects.get(id=partnership.partner.id)
        new_advertiser = user.objects.get(id=partnership.advertiser.id)

        new_partnership = ProjectPartner(
            id=partnership.id,
            project=new_project, 
            partner=new_partner, 
            advertiser=new_advertiser,
            status=partnership.status, 
            joined_at=partnership.joined_at, 
            suspension_reason=partnership.suspension_reason, 
            suspension_comment=partnership.suspension_comment 
        ) 

        project_partner_instances.append(new_partnership)
    
    ProjectPartner.objects.bulk_create(project_partner_instances, batch_size=1000) 
    schema_editor.execute("""
        SELECT setval('partnerships_projectpartner_id_seq',
        (SELECT COALESCE(MAX(id), 1) FROM partnerships_projectpartner), true); 
    """)

def reverse_migrate_projects(apps, schema_editor):
    NewPartnership = apps.get_model('partnerships', 'ProjectPartner')    
    NewPartnership.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0110_migrate_projects'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_partnerships,reverse_code=reverse_migrate_projects)
    ]
