# Generated by Django 5.1.6 on 2025-10-06 14:43

from django.db import migrations


def migrate_project_parameters(apps,schema_editor):
    old_param = apps.get_model('partner_app','ProjectParam')
    new_param = apps.get_model('advertisers','ProjectParam')
    new_project = apps.get_model('advertisers','Project')
    old_param_list = old_param.objects.all()
    new_param_list = []

    for param in old_param_list:
        project = new_project.objects.get(id = param.project.id)
        new_param_obj = new_param(
            id=param.id,
            project=project,
            name=param.name,
            description=param.description,
            param_type=param.param_type,
            example_value=param.example_value
        )
        new_param_list.append(new_param_obj)

    new_param.objects.bulk_create(new_param_list, batch_size=1000) 
    schema_editor.execute("""
        SELECT setval('advertisers_projectparam_id_seq',
        (SELECT COALESCE(MAX(id), 1) FROM advertisers_projectparam), true); 
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0112_alter_advertiserprofile_user_and_more'),
        ('advertisers','0007_projectparam')
    ]

    operations = [
        migrations.RunPython(migrate_project_parameters)
    ]
