# Generated by Django 5.1.6 on 2025-10-07 07:12

from django.db import migrations


def migrate_managers(apps,schema_editor):
    old_manager = apps.get_model('partner_app','ManagerProfile')
    new_manager = apps.get_model('managers','ManagerProfile')

    user = apps.get_model('users','User')

    old_managers = old_manager.objects.all()

    new_managers = []

    for manager in old_managers:
        new_user = user.objects.get(id=manager.user.id)
        new_manager_obj = new_manager(
            id = manager.id,
            user = new_user
        )

        new_managers.append(new_manager_obj)

    new_manager.objects.bulk_create(new_managers,batch_size=1000)
    schema_editor.execute("""
        SELECT setval('managers_managerprofile_id_seq',
        (SELECT COALESCE(MAX(id), 1) FROM managers_managerprofile), true); 
    """)

def reverse_migrate_managers(apps,schema_editor):
    manager = apps.get_model('managers','ManagerProfile')
    manager.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0114_migrate_partner_links'),
        ('managers','0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_managers,reverse_code=reverse_migrate_managers)
    ]
