# Generated by Django 5.1.6 on 2025-06-20 08:04

from django.db import migrations

import uuid 
def fill_uuids(apps, schema_editor):
    User = apps.get_model('partner_app', 'User')
    for user in User.objects.all():
        user.new_id = uuid.uuid4()
        user.save(update_fields=['new_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0002_user_new_id'),
    ]

    operations = [
        
    ]
