# Generated by Django 5.1.6 on 2025-06-20 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0003_populate_uuids'),
    ]

    operations = [
    ]
