# Generated by Django 5.1.6 on 2025-06-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0004_alter_user_new_id'),
    ]

    operations = [
        
    ]

