# Generated by Django 5.1.6 on 2025-06-27 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0019_alter_platform_platform_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(help_text='Например: TikTok-канал о кулинарии', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='На модерации', verbose_name='Статус'),
        ),
    ]
