# Generated by Django 5.1.6 on 2025-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0021_alter_platform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=False, verbose_name='Email уведомления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('partner', 'Партнёр'), ('advertiser', 'Рекламодатель'), ('manager', 'Менеджер')], default='Партнёр', max_length=20),
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
    ]
