# Generated by Django 5.1.6 on 2025-07-01 10:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0022_user_email_notifications_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(help_text='Например: TikTok-канал о кулинарии', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название площадки'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='partner_platforms', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='status',
            field=models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked')], default='На модерации', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Интернет магазин', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название проекта')),
                ('description', models.CharField(help_text='Например: Интернет магазин с быстрой доставкой, дешёвыми ценами и большим ассортиментом', max_length=300, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание проекта')),
                ('url', models.CharField(default='', help_text='Ссылка или идентификатор (@username, channel ID)', max_length=150, verbose_name='URL или ID')),
                ('min_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мин. выплата')),
                ('commission_rate', models.PositiveIntegerField(default=0, verbose_name='Комиссия (%)')),
                ('cookie_lifetime', models.PositiveIntegerField(default=0, verbose_name='Срок действия cookie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('status', models.CharField(choices=[('На модерации', 'Pending'), ('Подтверждено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked')], default='На модерации', verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True)),
                ('advertiser', models.ForeignKey(limit_choices_to={'user_type': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Подтверждён ли доступ партнёра к проекту')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_projects', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_partners', to='partner_app.project')),
            ],
            options={
                'unique_together': {('project', 'partner')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(limit_choices_to={'user_type': 'partner'}, related_name='projects', through='partner_app.ProjectPartner', to=settings.AUTH_USER_MODEL, verbose_name='Партнёры проекта'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('advertiser', 'url'), name='unique_advertiser_project'),
        ),
    ]
