# Generated by Django 5.1.6 on 2025-07-03 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0027_alter_advertiserprofile_api_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='platform',
            name='description',
            field=models.CharField(default='Описание', help_text='Например: Блог о путешествиях', max_length=300, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание проекта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('partner', 'Партнёр'), ('advertiser', 'Рекламодатель'), ('manager', 'Менеджер')], default='partner', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
