# Generated by Django 5.1.6 on 2025-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0029_alter_platform_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpartner',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='status',
            field=models.CharField(choices=[('На модерации', 'Pending'), ('Одобрено', 'Approved'), ('Отклонено', 'Rejected'), ('Заблокировано', 'Blocked')], default='На модерации', help_text='Подтверждён ли доступ партнёра к проекту', verbose_name='Статус взаимодействия'),
        ),
    ]
