# Generated by Django 5.1.6 on 2025-07-08 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0031_projectpartner_custom_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мин. выплата'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Мин. выплата'),
        ),
    ]
