# Generated by Django 5.1.5 on 2025-07-21 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0033_alter_projectpartner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartnerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('total_conversions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Статистика о сотрудничестве партнёра с проектом',
            },
        ),
        migrations.AlterModelOptions(
            name='advertiserprofile',
            options={'verbose_name': 'Рекламодатель', 'verbose_name_plural': 'Рекламодатели'},
        ),
        migrations.AlterModelOptions(
            name='managerprofile',
            options={'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='projectpartner',
            options={'verbose_name': 'Партнёр проекта'},
        ),
        migrations.RemoveField(
            model_name='projectpartner',
            name='joined_at',
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='custom_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='status',
            field=models.CharField(choices=[('Активен', 'Активен'), ('Приостановлен', 'Приостановлен'), ('Заблокировано', 'Заблокировано')], default='Активен', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_link', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_link', to='partner_app.project')),
            ],
            options={
                'verbose_name': 'Партнёрская ссылка',
                'unique_together': {('partner', 'project')},
            },
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='partner_link',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_link', to='partner_app.partnerlink'),
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership', to='partner_app.projectpartnerstats'),
        ),
        migrations.CreateModel(
            name='PartnerClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_unique', models.BooleanField(default=True)),
                ('project_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='partner_app.projectpartner')),
            ],
            options={
                'indexes': [models.Index(fields=['project_partner', 'timestamp'], name='partner_app_project_45bfb4_idx')],
            },
        ),
    ]
