# Generated by Django 5.1.5 on 2025-07-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0034_projectpartnerstats_alter_advertiserprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='partnerlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='partnerlink',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='partnerlink',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectpartner',
            name='partner_link',
        ),
        migrations.RemoveField(
            model_name='projectpartner',
            name='stats',
        ),
        migrations.DeleteModel(
            name='PartnerClick',
        ),
        migrations.DeleteModel(
            name='PartnerLink',
        ),
        migrations.DeleteModel(
            name='ProjectPartnerStats',
        ),
    ]
