# Generated by Django 5.1.5 on 2025-07-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0035_alter_partnerlink_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpartner',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
