# Generated by Django 5.1.5 on 2025-07-22 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0038_alter_projectpartner_options_partnerlink_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Партнёрская ссылка', 'verbose_name_plural': 'Партнёрские ссылки'},
        ),
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'verbose_name': 'Профиль партнёра', 'verbose_name_plural': 'Профили партнёров'},
        ),
        migrations.AlterField(
            model_name='partnerlink',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partnerlink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='partner_app.project'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='traffic_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Источник трафика'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerlink',
            unique_together={('partner', 'project')},
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_link', models.URLField(blank=True, max_length=512, verbose_name='Целевой URL')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('clicked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('converted', models.BooleanField(default=False)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='partner_app.projectpartner')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['partner_link', 'clicked_at'], name='partner_app_partner_9a586a_idx')],
            },
        ),
    ]
