# Generated by Django 5.1.5 on 2025-07-22 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0039_alter_partnerlink_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='partner_app.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='clicked_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата клика'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='converted',
            field=models.BooleanField(default=False, verbose_name='Конверсия'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='partner_link',
            field=models.URLField(blank=True, default=None, max_length=512, null=True, verbose_name='Целевой URL'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='referer',
            field=models.URLField(blank=True, verbose_name='Источник перехода'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['ip_address'], name='partner_app_ip_addr_372381_idx'),
        ),
    ]
