# Generated by Django 5.1.5 on 2025-07-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0040_clickevent_project_alter_clickevent_clicked_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='PartnerLink',
            name='id',
        ),
        migrations.DeleteModel(
            name='ClickEvent',
        ),
    ]
