# Generated by Django 5.1.5 on 2025-07-24 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0043_alter_conversion_meta_alter_conversion_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link_template',
            field=models.CharField(blank=True, default='', help_text='Используйте {param} для параметров, например: https://site.com?pid={partner_id}', max_length=500, verbose_name='Шаблон ссылки'),
        ),
        migrations.CreateModel(
            name='ProjectParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя параметра')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('param_type', models.CharField(choices=[('required', 'Обязательный'), ('optional', 'Опциональный')], default='optional', max_length=10, verbose_name='Тип параметра')),
                ('example_value', models.CharField(blank=True, max_length=100, verbose_name='Пример значения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='partner_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Параметр проекта',
                'verbose_name_plural': 'Параметры проекта',
                'unique_together': {('project', 'name')},
            },
        ),
    ]
