# Generated by Django 5.1.6 on 2025-07-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0044_project_link_template_projectparam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectparam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма конверсии'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link_template',
            field=models.CharField(blank=True, default=None, help_text='Введите адрес партнёрской ссылки и добавьте ниже необходимые параметры', max_length=500, null=True, verbose_name='Шаблон ссылки'),
        ),
    ]
