# Generated by Django 5.1.6 on 2025-07-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0045_alter_projectparam_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpartner',
            name='partner_link',
            field=models.CharField(blank=True, default=None, null=True, verbose_name='Партнёрская ссылка'),
        ),
    ]
