# Generated by Django 5.1.5 on 2025-07-30 17:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0046_projectpartner_partner_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, validators=[django.core.validators.URLValidator()], verbose_name='Базовая ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Количество переходов')),
                ('conversions', models.PositiveIntegerField(default=0, verbose_name='Количество конверсий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='partner_app.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Партнёрская ссылка',
                'verbose_name_plural': 'Партнёрские ссылки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='partner_link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner_app.partnerlink', verbose_name='Партнёрская ссылка'),
        ),
        migrations.AddIndex(
            model_name='partnerlink',
            index=models.Index(fields=['user', 'is_active'], name='partner_app_user_id_2426fb_idx'),
        ),
    ]
