# Generated by Django 5.1.6 on 2025-07-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0048_partnerlink_partnership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpartner',
            name='partner_link',
        ),
        migrations.DeleteModel(
            name='PartnerLink',
        ),
    ]
