# Generated by Django 5.1.6 on 2025-07-31 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0051_partnerlink_partnership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlink',
            name='partnership',
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='partner_link',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_link', to='partner_app.partnerlink', verbose_name='Партнёрская ссылка'),
        ),
    ]
