# Generated by Django 5.1.6 on 2025-07-31 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0052_remove_partnerlink_partnership_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlink',
            name='clicks',
        ),
        migrations.RemoveField(
            model_name='partnerlink',
            name='conversions',
        ),
        migrations.RemoveField(
            model_name='projectpartner',
            name='partner_link',
        ),
        migrations.AddField(
            model_name='conversion',
            name='partner_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.partnerlink'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.platform'),
        ),
        migrations.AddField(
            model_name='partnerlink',
            name='partnership',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='partner_links', to='partner_app.projectpartner', verbose_name='Сотрудничество партнёра с проектом'),
        ),
    ]
