# Generated by Django 5.1.5 on 2025-07-31 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0053_remove_partnerlink_clicks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.URLField(blank=True, default=None, null=True, verbose_name='Источник')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата клика')),
                ('partner', models.ForeignKey(blank=True, help_text='Необязательно, если клик не от партнёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to=settings.AUTH_USER_MODEL, verbose_name='ID партнёра')),
                ('partner_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.partnerlink', verbose_name='партнёрская ссылка')),
                ('platform', models.ForeignKey(blank=True, help_text='Необязательно, если клик не с площадки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.platform', verbose_name='ID площадки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.project', verbose_name='ID проекта')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'indexes': [models.Index(fields=['project'], name='partner_app_project_7d1f5a_idx'), models.Index(fields=['partner'], name='partner_app_partner_f004cf_idx'), models.Index(fields=['platform'], name='partner_app_platfor_a87d41_idx'), models.Index(fields=['created_at'], name='partner_app_created_017f38_idx')],
            },
        ),
    ]
