# Generated by Django 5.1.6 on 2025-08-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0054_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerlink',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход'),
        ),
    ]
