# Generated by Django 5.1.6 on 2025-08-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0055_partnerlink_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='partnership',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.projectpartner', verbose_name='Сотрудничество партнёра с проектом'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='partnership',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.projectpartner', verbose_name='Сотрудничество партнёра с проектом'),
        ),
    ]
