# Generated by Django 5.1.6 on 2025-08-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0056_clickevent_partnership_conversion_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход'),
        ),
    ]
