# Generated by Django 5.1.6 on 2025-08-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0057_platform_income'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversion',
            options={'verbose_name': 'Конверсия', 'verbose_name_plural': 'Конверсии'},
        ),
        migrations.CreateModel(
            name='PartnerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('sale', 'Новая продажа'), ('clicks', 'Переходы по ссылке'), ('payout', 'Выплата'), ('bonus', 'Бонус'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип активности')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Детали')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Активность партнёра',
                'verbose_name_plural': 'Активности партнёров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'is_read'], name='partner_app_partner_737a0f_idx')],
            },
        ),
    ]
