# Generated by Django 5.1.6 on 2025-08-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0059_remove_partneractivity_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerlink',
            name='income',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='income',
        ),
        migrations.RemoveField(
            model_name='projectpartner',
            name='total_income',
        ),
    ]
