# Generated by Django 5.1.6 on 2025-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0061_alter_partneractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversion',
            name='partner_app_order_i_c7bba7_idx',
        ),
        migrations.RenameField(
            model_name='conversion',
            old_name='meta',
            new_name='details',
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['project'], name='partner_app_project_84e37f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['partner'], name='partner_app_partner_8b1fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['partnership'], name='partner_app_partner_883a76_idx'),
        ),
    ]
