# Generated by Django 5.1.6 on 2025-08-11 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0064_alter_partnertransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpayoutsettings',
            name='partner',
            field=models.OneToOneField(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_settings', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр'),
        ),
    ]
