# Generated by Django 5.1.6 on 2025-08-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0066_alter_partnertransaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnertransaction',
            name='description',
        ),
    ]
