# Generated by Django 5.1.6 on 2025-08-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0067_remove_partnertransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnertransaction',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Укажите причину, если транзакция отклонена', null=True, verbose_name='Причина отклонения'),
        ),
    ]
