# Generated by Django 5.1.6 on 2025-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0069_alter_partnerpayoutsettings_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerpayoutsettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
    ]
