# Generated by Django 5.1.6 on 2025-08-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0070_alter_partnerpayoutsettings_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerpayoutsettings',
            name='bank_bic',
        ),
    ]
