# Generated by Django 5.1.5 on 2025-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0071_remove_partnerpayoutsettings_bank_bic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpartner',
            name='suspension_comment',
            field=models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Доп. комментарий к приостановке сотрудничества'),
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='suspension_reason',
            field=models.TextField(blank=True, default=None, help_text='Например: Тех. работы', max_length=50, null=True, verbose_name='Причина приостановления сотрудничества'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Pending'), ('Выплачено', 'Completed'), ('Отменено', 'Rejected')], default='В обработке', max_length=20, verbose_name='Статус транзакции'),
        ),
    ]
