# Generated by Django 5.1.6 on 2025-08-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0072_projectpartner_suspension_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocking_reason',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Причина блокировки'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
