# Generated by Django 5.1.6 on 2025-08-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0073_user_block_until_user_blocking_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User-Agent'),
        ),
    ]
