# Generated by Django 5.1.6 on 2025-08-15 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0074_conversion_ip_address_conversion_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cookie_lifetime',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_payout',
        ),
        migrations.AddField(
            model_name='project',
            name='cost_per_action',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за действие'),
        ),
    ]
