# Generated by Django 5.1.6 on 2025-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0075_remove_project_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpartner',
            name='custom_commission',
        ),
        migrations.AddField(
            model_name='projectpartner',
            name='cost_per_action',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена за действие'),
        ),
    ]
