# Generated by Django 5.1.6 on 2025-08-15 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0078_remove_projectpartner_cost_per_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='first_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена за действие'),
        ),
    ]
