# Generated by Django 5.1.6 on 2025-08-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0079_project_first_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.advertiserprofile'),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partner_app.partnerprofile'),
        ),
    ]
