# Generated by Django 5.1.6 on 2025-08-15 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0080_conversion_advertiser_alter_conversion_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.advertiserprofile', verbose_name='ID рекламодателя'),
        ),
        migrations.AlterField(
            model_name='clickevent',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Необязательно, если клик не от партнёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partner_app.partnerprofile', verbose_name='ID партнёра'),
        ),
    ]
