# Generated by Django 5.1.6 on 2025-08-19 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0082_remove_conversion_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost_per_action',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Цена за действие'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Например: Интернет магазин с быстрой доставкой, дешёвыми ценами и большим ассортиментом', max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание проекта'),
        ),
    ]
