# Generated by Django 5.1.6 on 2025-08-20 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0083_alter_project_cost_per_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cost_per_action',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Цена за действие'),
        ),
        migrations.AlterField(
            model_name='project',
            name='first_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Первоначальная цена'),
        ),
    ]
