# Generated by Django 5.1.6 on 2025-08-20 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0084_alter_project_cost_per_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='description',
            field=models.CharField(help_text='Например: Блог о путешествиях', max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание площадки'),
        ),
    ]
