# Generated by Django 5.1.6 on 2025-08-25 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0085_alter_platform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnertransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(300)], verbose_name='Сумма'),
        ),
        migrations.CreateModel(
            name='AdvertiserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(300)], verbose_name='Сумма')),
                ('payment_method', models.CharField(choices=[('wallet', 'Электронный кошелёк'), ('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('sbp', 'Система быстрых платежей (СБП)')], default='card', max_length=20, verbose_name='Способ пополнения')),
                ('status', models.CharField(choices=[('В обработке', 'Pending'), ('Пополнено', 'Completed'), ('Отменено', 'Rejected')], default='В обработке', max_length=20, verbose_name='Статус транзакции')),
                ('rejection_reason', models.TextField(blank=True, help_text='Укажите причину, если транзакция отклонена', null=True, verbose_name='Причина отклонения')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='partner_app.advertiserprofile', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Пополнение',
                'verbose_name_plural': 'Пополнения',
                'ordering': ['-date'],
            },
        ),
    ]
