# Generated by Django 5.1.6 on 2025-08-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0086_alter_partnertransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='advertisertransaction',
            name='status',
            field=models.CharField(choices=[('В обработке', 'Pending'), ('Обработано', 'Proccessed'), ('Пополнено', 'Completed'), ('Отменено', 'Rejected')], default='В обработке', max_length=20, verbose_name='Статус транзакции'),
        ),
    ]
