# Generated by Django 5.1.6 on 2025-08-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0087_user_middle_name_alter_advertisertransaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='position',
        ),
        migrations.RemoveField(
            model_name='partnerprofile',
            name='traffic_source',
        ),
    ]
