# Generated by Django 5.1.6 on 2025-08-29 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0089_alter_advertiseractivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='checking_account',
            field=models.CharField(max_length=20, unique=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='correspondent_account',
            field=models.CharField(max_length=20, unique=True, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='legal_address',
            field=models.TextField(blank=True, help_text='Почтовый индекс, город, улица, дом', null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+79999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
