# Generated by Django 5.1.6 on 2025-09-03 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0090_alter_advertiserrequisites_checking_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='new_cost_per_action',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Цена за действие'),
        ),
    ]
