# Generated by Django 5.1.6 on 2025-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0091_project_new_cost_per_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_advertiser_project',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('url',), name='unique_project_url'),
        ),
    ]
