# Generated by Django 5.1.6 on 2025-09-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0092_remove_project_unique_advertiser_project_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_url',
        ),
    ]
