# Generated by Django 5.1.6 on 2025-09-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0093_remove_project_unique_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterField(
            model_name='advertiserprofile',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='API-ключ'),
        ),
    ]
