# Generated by Django 5.1.5 on 2025-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0094_alter_partnerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='bik',
            field=models.CharField(blank=True, default='', max_length=9, null=True, unique=True, verbose_name='БИК банка'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='checking_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Расчётный счёт'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='correspondent_account',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True, verbose_name='Корреспондентский счёт'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='inn',
            field=models.CharField(blank=True, default='', max_length=12, null=True, unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='ogrn',
            field=models.CharField(default='', max_length=15, unique=True, verbose_name='ОГРН / ОГРНИП'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='organization_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True, unique=True, verbose_name='Полное наименование организации'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='responsible_person',
            field=models.CharField(blank=True, default='', max_length=200, null=True, unique=True, verbose_name='ФИО ответственного лица'),
        ),
    ]
