# Generated by Django 5.1.6 on 2025-09-26 10:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0097_advertisertransaction_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('comment', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('status', models.CharField(choices=[('На модерации', 'Pending'), ('Опубликован', 'Published')], default='На модерации', verbose_name='Статус')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата клика')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Отзывы пользователя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'indexes': [models.Index(fields=['user'], name='partner_app_user_id_0c9fb0_idx'), models.Index(fields=['name'], name='partner_app_name_96daf5_idx'), models.Index(fields=['comment'], name='partner_app_comment_debf87_idx'), models.Index(fields=['created_at'], name='partner_app_created_89a41f_idx')],
            },
        ),
    ]
