# Generated by Django 5.1.6 on 2025-10-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0098_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
