# Generated by Django 5.1.6 on 2025-10-03 14:30

from django.db import migrations


def move_partner_notifications(apps, schema_editor):
    OldNotification = apps.get_model('partner_app', 'PartnerActivity')
    NewNotification = apps.get_model('partners', 'PartnerActivity')
    old_notifications = OldNotification.objects.all()
    Partner = apps.get_model('partners', 'PartnerProfile')
    
    new_partner_notifications = []
    for notification in old_notifications:

        user = Partner.objects.get(id=notification.partner.id)

        new_notification = NewNotification(
            id=notification.id,          
            partner=user,
            activity_type=notification.activity_type,
            title=notification.title,
            details=notification.details,
            is_read=notification.is_read,
            created_at=notification.created_at
        )
        new_partner_notifications.append(new_notification)
    
    NewNotification.objects.bulk_create(new_partner_notifications, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0101_auto_20251003_1304'),
        ('partners', '0002_partneractivity'),
    ]

    operations = [migrations.RunPython(move_partner_notifications)]
