# Generated by Django 5.1.6 on 2025-10-06 06:33

from django.db import migrations

def move_partner_platforms(apps,schema_editor):
    old_platform = apps.get_model('partner_app', 'Platform')
    NewPlatform = apps.get_model('partners', 'Platform')
    old_platforms = old_platform.objects.all()
    Partner = apps.get_model('users', 'user')
    new_platforms = []
    for old_platform in old_platforms:
        user = Partner.objects.get(id=old_platform.partner.id)

        new_platform = NewPlatform(
            id=old_platform.id,
            partner=user,
            name=old_platform.name,
            description=old_platform.description,
            platform_type=old_platform.platform_type,
            url_or_id=old_platform.url_or_id,
            created_at=old_platform.created_at,
            status=old_platform.status,
            is_active=old_platform.is_active
        )

        new_platforms.append(new_platform)

    NewPlatform.objects.bulk_create(new_platforms, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0102_auto_20251003_1730'),
        ('partners', '0003_platform'),
    ]

    operations = [
        migrations.RunPython(move_partner_platforms)
    ]
