# Generated by Django 5.1.6 on 2025-10-06 07:16

from django.db import migrations


def migrate_partner_payout_settings(apps,schema_editor):
    old_settings = apps.get_model('partner_app','PartnerPayoutSettings')
    NewSettings = apps.get_model('partners','PartnerPayoutSettings')
    old_settings_all = old_settings.objects.all()

    partner = apps.get_model('users','User')
   
    new_settings_lst = []

    for settings in old_settings_all:
        user = partner.objects.get(id = settings.partner.id)

        new_settings_obj = NewSettings(
            id=settings.id,
            partner=user,
            payout_method=settings.payout_method,

            card_number=settings.card_number,
            cardholder_name=settings.cardholder_name,
            bank_name=settings.bank_name,

            bank_account_number=settings.bank_account_number,
            bank_account_holder_name=settings.bank_account_holder_name,
            bank_account_bic=settings.bank_account_bic,

            e_wallet_identifier=settings.e_wallet_identifier,

            sbp_identifier=settings.sbp_identifier,
            created_at=settings.created_at,
            updated_at=settings.updated_at,
            active_payout_method=settings.active_payout_method
        )
        new_settings_lst.append(new_settings_obj)

    NewSettings.objects.bulk_create(new_settings_lst, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0103_auto_20251006_0933'),
        ('partners','0004_partnerpayoutsettings')
    ]

    operations = [
        migrations.RunPython(migrate_partner_payout_settings)
    ]
