# Generated by Django 5.1.6 on 2025-10-06 12:17

from django.db import migrations

def migrate_advertiser_transactions(apps,schema_editor):
    old_transaction = apps.get_model('partner_app','AdvertiserTransaction')
    NewTransaction = apps.get_model('advertisers','AdvertiserTransaction')
    old_transactions = old_transaction.objects.all()

    advertiser = apps.get_model('advertisers','AdvertiserProfile')
   
    new_transactions = []

    for transaction in old_transactions:
        adv_user = advertiser.objects.get(id = transaction.advertiser.id)

        new_transaction = NewTransaction(
            id=transaction.id,
            advertiser=adv_user,
            date=transaction.date,
            amount=transaction.amount,
            payment_method=transaction.payment_method,
            status=transaction.status,
            rejection_reason=transaction.rejection_reason,
            is_read=transaction.is_read
        )
        new_transactions.append(new_transaction)

    NewTransaction.objects.bulk_create(new_transactions, batch_size=1000)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0107_migrate_advertiser_activity'),
        ('advertisers','0003_advertisertransaction')
    ]

    operations = [
        migrations.RunPython(migrate_advertiser_transactions)
    ]
