# Generated by Django 5.1.6 on 2025-10-06 12:40

from django.db import migrations

def migrate_advertiser_requisites(apps,schema_editor):
    old_settings = apps.get_model('partner_app','AdvertiserRequisites')
    NewSettings = apps.get_model('advertisers','AdvertiserRequisites')
    old_settings_all = old_settings.objects.all()

    advertiser = apps.get_model('users','User')
   
    new_settings_lst = []

    for settings in old_settings_all:
        user = advertiser.objects.get(id = settings.user.id)

        new_settings_obj = NewSettings(
            id=settings.id,
            user=user,

            responsible_person=settings.responsible_person,
            organization_name=settings.organization_name,
            legal_address=settings.legal_address,
            phone=settings.phone,
            email=settings.email,
            ogrn=settings.ogrn,
            inn=settings.inn,
            checking_account=settings.checking_account,
            correspondent_account=settings.correspondent_account,
            bik=settings.bik,
            created_at=settings.created_at,
            updated_at=settings.updated_at,
        )
        new_settings_lst.append(new_settings_obj)

    NewSettings.objects.bulk_create(new_settings_lst, batch_size=1000)

    schema_editor.execute("""
        SELECT setval('advertisers_advertiserrequisites_id_seq', 
        (SELECT COALESCE(MAX(id), 1) FROM advertisers_advertiserrequisites), true);
    """)

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0108_migrate_advertiser_transactions'),
        ('advertisers','0004_advertiserrequisites')
    ]

    operations = [
        migrations.RunPython(migrate_advertiser_requisites)
    ]
