# Generated by Django 5.1.6 on 2025-10-06 13:44

from django.db import migrations
from decimal import Decimal


def migrate_projects(apps, schema_editor):
    OldProject = apps.get_model('partner_app', 'Project')
    NewProject = apps.get_model('advertisers', 'Project')

    old_projects = OldProject.objects.all()
    new_projects = []

    for old in old_projects:
        new_proj = NewProject(
            id=old.id,
            advertiser_id=old.advertiser_id,
            name=old.name,
            description=old.description,
            url=old.url,
            new_cost_per_action=old.new_cost_per_action or None,
            cost_per_action=old.cost_per_action or Decimal('5.00'),
            first_price=old.first_price or Decimal('5.00'),
            created_at=old.created_at,
            status=old.status,
            link_template=old.link_template,
            is_active=old.is_active,
        )
        new_projects.append(new_proj)



    NewProject.objects.bulk_create(new_projects, batch_size=1000)
    schema_editor.execute("""
        SELECT setval('advertisers_project_id_seq', 
        (SELECT COALESCE(MAX(id), 1) FROM advertisers_project), true);
    """)

def reverse_migrate_projects(apps, schema_editor):
    NewProject = apps.get_model('advertisers', 'Project')    
    NewProject.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0109_migrate_advertiser_requisites'),
        ('advertisers', '0005_project'),
        ('advertisers', '0006_project_partners'),
    ]

    operations = [
        migrations.RunPython(migrate_projects,reverse_code=reverse_migrate_projects)
    ]
