# Generated by Django 5.1.6 on 2025-10-07 06:33

from django.db import migrations


def migrate_partner_links(apps,schema_editor):
    old_link = apps.get_model('partner_app','PartnerLink')
    NewLink = apps.get_model('partners','PartnerLink')

    partner = apps.get_model('users','User')
    project = apps.get_model('advertisers','Project')
    partnership = apps.get_model('partnerships','ProjectPartner')

    old_links = old_link.objects.all()

    new_links = []
    for link in old_links:
        new_partner = partner.objects.get(id=link.partner.id)
        new_project = project.objects.get(id=link.project.id)
        new_partnership = partnership.objects.get(id=link.partnership.id)

        new_link = NewLink(
            id=link.id,
            partner=new_partner,
            project=new_project,
            partnership=new_partnership,
            url=link.url,
            created_at=link.created_at,
            is_active=link.is_active

        )

        new_links.append(new_link)

    NewLink.objects.bulk_create(new_links, batch_size=1000)
    schema_editor.execute("""
        SELECT setval('partners_partnerlink_id_seq',
        (SELECT COALESCE(MAX(id), 1) FROM partners_partnerlink), true); 
    """)
        
        
def reverse_migrate_partner_links(apps, schema_editor):
    NewLinks = apps.get_model('partners', 'PartnerLink')    
    NewLinks.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0113_migrate_project_param'),
        ('partners','0006_partnerlink')
    ]

    operations = [
        migrations.RunPython(migrate_partner_links,reverse_code=reverse_migrate_partner_links)
    ]
