# Generated by Django 5.1.6 on 2025-10-08 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0007_projectparam'),
        ('partner_app', '0117_migrate_clicks'),
        ('partners', '0006_partnerlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiseractivity',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='advertisers.advertiserprofile', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advertisertransaction',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='advertisers.advertiserprofile', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='partneractivity',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partners.partnerprofile', verbose_name='Партнёр'),
        ),
    ]
