# Generated by Django 5.1.6 on 2025-10-08 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_app', '0119_alter_advertiserprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiseractivity',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.advertiserprofile', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='advertiserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user'),
        ),
        migrations.AlterField(
            model_name='advertiserrequisites',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user'),
        ),
        migrations.AlterField(
            model_name='advertisertransaction',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.advertiserprofile', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='partneractivity',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.partnerprofile', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='partnerlink',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='partnerpayoutsettings',
            name='partner',
            field=models.OneToOneField(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='partnertransaction',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'partner'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='project',
            name='advertiser',
            field=models.ForeignKey(limit_choices_to={'user_type': 'advertiser'}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'partner'}, related_name='+', through='partner_app.ProjectPartner', to='partner_app.user', verbose_name='Партнёры проекта'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='advertiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Рекламодатель'),
        ),
        migrations.AlterField(
            model_name='projectpartner',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='partner_app.user', verbose_name='Партнёр'),
        ),
    ]
