# Generated by Django 5.1.6 on 2025-10-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0005_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Активен', 'Активен'), ('Приостановлен', 'Приостановлен'), ('Заблокировано', 'Заблокировано')], default='Активен', max_length=20, verbose_name='Статус сотрудничества')),
                ('joined_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата начала сотрудничества')),
                ('suspension_reason', models.TextField(blank=True, default=None, help_text='Например: Тех. работы', max_length=50, null=True, verbose_name='Причина приостановления сотрудничества')),
                ('suspension_comment', models.TextField(blank=True, default=None, max_length=300, null=True, verbose_name='Доп. комментарий к приостановке сотрудничества')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL, verbose_name='Рекламодатель')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Партнёр')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to='advertisers.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Партнёрство в проекте',
                'verbose_name_plural': 'Партнёрства в проектах',
                'unique_together': {('project', 'partner')},
            },
        ),
    ]
