# Generated by Django 5.1.6 on 2025-10-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0007_projectparam'),
        ('partners', '0006_partnerlink'),
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма конверсии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='advertisers.advertiserprofile')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partners.partnerprofile')),
                ('partner_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partners.partnerlink')),
                ('partnership', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partnerships.projectpartner', verbose_name='Сотрудничество партнёра с проектом')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='partners.platform')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='advertisers.project')),
            ],
            options={
                'verbose_name': 'Конверсия',
                'verbose_name_plural': 'Конверсии',
                'indexes': [models.Index(fields=['project'], name='tracking_co_project_ee0958_idx'), models.Index(fields=['partner'], name='tracking_co_partner_086f20_idx'), models.Index(fields=['partnership'], name='tracking_co_partner_6384d4_idx'), models.Index(fields=['created_at'], name='tracking_co_created_521a36_idx')],
            },
        ),
    ]
