# Generated by Django 5.1.6 on 2025-10-07 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0007_projectparam'),
        ('partners', '0006_partnerlink'),
        ('partnerships', '0001_initial'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.URLField(blank=True, default=None, null=True, verbose_name='Источник')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата клика')),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='advertisers.advertiserprofile', verbose_name='ID рекламодателя')),
                ('partner', models.ForeignKey(blank=True, help_text='Необязательно, если клик не от партнёра', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partners.partnerprofile', verbose_name='ID партнёра')),
                ('partner_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partners.partnerlink', verbose_name='партнёрская ссылка')),
                ('partnership', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partnerships.projectpartner', verbose_name='Сотрудничество партнёра с проектом')),
                ('platform', models.ForeignKey(blank=True, help_text='Необязательно, если клик не с площадки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='partners.platform', verbose_name='ID площадки')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='advertisers.project', verbose_name='ID проекта')),
            ],
            options={
                'verbose_name': 'Клик',
                'verbose_name_plural': 'Клики',
                'indexes': [models.Index(fields=['project'], name='tracking_cl_project_8e53bf_idx'), models.Index(fields=['partner'], name='tracking_cl_partner_ff2b96_idx'), models.Index(fields=['platform'], name='tracking_cl_platfor_3bdbfd_idx'), models.Index(fields=['created_at'], name='tracking_cl_created_cec036_idx')],
            },
        ),
    ]
